sudo: false
language: python
python:
  - "3.5"
env:
  - JEKYLL_ENV=production
before_install:
  - rvm use 2.2.3 --install --fuzzy

install:
 - gem install --no-document jekyll
 - pip install --use-wheel jupyter

script:
 - make deploy
