layouts_dir:  ./_jekyll/_layouts

exclude:
  - README.markdown
  - LICENSE
  - Makefile
  - deploy.sh
  - requirements.txt
  - CAD
  - nb-markdown.tpl
  - matplotlibrc
  - "GSE/*.fcstd"
  - "GSE/*.step"
  - simulation/24mm_minimum_dia.ork
  - simulation/requirements.txt
  - simulation/matplotlibrc
  - simulation/56-F31-12A_openrocketsim.csv
  - "simulation/*.ipynb"
encoding: "utf-8"
markdown: kramdown
kramdown:
  toc_levels: "2,3"
excerpt_separator: "\n\n\n\n"
permalink: :categories/:year/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "article"
